tehnologiiWeb/Controllers/ItemsListController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using tehnologiiWeb.DataAccess;
using System.Threading.Tasks;
using tehnologiiWeb.Web.Models;
using tehnologiiWeb.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace tehnologiiWeb.Web.Controllers
{
   [Authorize]
    public class ItemsListController : Controller
    {
        private readonly ApplicationDbContext _Db;

        public ItemsListController(ApplicationDbContext Db)
        {
            _Db = Db;
        }

        public IActionResult Index()
        {

            ViewBag.items = _Db.items.ToList();
            return View();
        }

        public async Task<IActionResult> Create(int? id)
        {
            if(id is null)
            {
                return View(new ItemsViewModel());
            }   

            var itemFromDb = await _Db.items.FirstOrDefaultAsync(item => item.Id == id.Value);
            if (itemFromDb is null)
            {
                ViewBag.message = "Invalid data";
                return View(new ItemsViewModel());
            }

            var r = new ItemsViewModel { Id = itemFromDb.Id,
                                         Category = itemFromDb.Category,
                                         Email = itemFromDb.Email,
                                         Owner = itemFromDb.Owner, 
                                         Name = itemFromDb.Name, 
                                         Price = itemFromDb.Price, 
                                         StringUrl = itemFromDb.StringUrl };


            return View(r);
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(ItemsViewModel model)
        { 
            if (model.Id == null)
            {
                var itemModel = new Item();

                if (ModelState.IsValid)
                {
                    itemModel.Name = model.Name;
                    itemModel.Owner = model.Owner;
                    itemModel.Price = model.Price;
                    itemModel.StringUrl = model.StringUrl;
                    itemModel.Email = model.Email;
                    itemModel.Category = model.Category;
             
                    await _Db.items.AddAsync(itemModel);
                    await _Db.SaveChangesAsync();
                    return RedirectToAction("Index"); 
                }

                return ViewBag.message = "Incorect data";
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var itemFromDb = await _Db.items.FindAsync(model.Id);
                    itemFromDb.Name = model.Name;
                    itemFromDb.Owner = model.Owner;
                    itemFromDb.Email = model.Email;

                    await _Db.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
                else
                {
                    return ViewBag.message = "Incorect data";
                }
            }

        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(ItemsViewModel model)
        {
            var item = await _Db.items.FindAsync(model.Id);
            if (item == null)
            {
                return NotFound();

            }
            _Db.items.Remove(item);
            await _Db.SaveChangesAsync();

            return RedirectToAction("Index");
        }


    }
}

tehnologiiWeb/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using tehnologiiWeb.Domain;
using System.Threading.Tasks;
using tehnologiiWeb.Web.Models;
using tehnologiiWeb.DataAccess;
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System;

namespace tehnologiiWeb.Web.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _Db;

        public LoginController(ApplicationDbContext Db)
        {
            _Db = Db;
        }

        [HttpGet]
        public IActionResult Index(string ReturnUrl = "/")
        {
            LoginViewModel objLoginModel = new LoginViewModel();
            objLoginModel.ReturnURL = ReturnUrl;
            return View(objLoginModel);
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _Db.accounts.FirstOrDefaultAsync(u => u.Username == model.Username && u.Password == model.Password);

                if (result == null)
                {
                    ViewBag.message = "Invalid credentials!";
                }
                else
                {
                    ViewBag.message = result.Role;

                    var claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.NameIdentifier, Convert.ToString(result.Id)),
                        new Claim(ClaimTypes.Name, result.Username),
                        new Claim(ClaimTypes.Role, result.Role)
                    };

                    //Initialize a new instance of the ClaimsIdentity with the claims and authentication scheme    
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    //Initialize a new instance of the ClaimsPrincipal with ClaimsIdentity    
                    var principal = new ClaimsPrincipal(identity);
                    //SignInAsync is a Extension method for Sign in a principal for the specified scheme.    
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, new AuthenticationProperties()
                    {
                        IsPersistent = model.RememberMe
                    });
                    return LocalRedirect(model.ReturnURL);
                }
            }
            return View(model);
        }

        public async Task<IActionResult> LogOut()
        {
            //SignOutAsync is Extension method for SignOut    
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            //Redirect to home page    
            return LocalRedirect("/");
        }
    }

}

tehnologiiWeb/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using tehnologiiWeb.DataAccess;
using tehnologiiWeb.Domain;
using tehnologiiWeb.Web.Models;

namespace tehnologiiWeb.Web.Controllers
{
    public class RegisterController : Controller
    {
        private readonly DbContext _Db;

        public IActionResult Index()
        {
            return View();
        }
        
        public RegisterController(ApplicationDbContext Db)
        {
            _Db = Db;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(RegisterViewModel model)
        {
            var newAccount = new Account();

            if (ModelState.IsValid)
            {
                newAccount.Username = model.Username;
                newAccount.FullName = model.FullName;
                newAccount.Email = model.Email;
                newAccount.Password = model.Password;

                _Db.Add(newAccount);
                _Db.SaveChanges();
                ViewBag.message = "The user " + newAccount.Username + " is saved successfully";
                    //await newAccount. SignInAsync(user, isPersistent: false);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.message = "Invalid credentials";
            }
            
            return View();
        }

    }
}

tehnologiiWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Enache Alina</title>
    <meta content="web technologies" name="description">
    <meta content="web, asp.net core, practice" name="keywords">

    <!-- Favicons -->
    <link href="/img/favicon.ico" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="/vendor/aos/aos.css" rel="stylesheet">
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="/css/style.css" rel="stylesheet">
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header">
        <div class="container d-flex align-items-center justify-content-lg-between">
            <h1 class="logo me-auto me-lg-0"><img src="/img/logo.png" /><a asp-controller="Home" asp-action="Index"> E-shop </a></h1>

            <!-- .navbar -->
            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a class="nav-link scrollto active" asp-controller="Home" asp-action="Index">Home</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link scrollto"  asp-controller="ItemsList" asp-action="Index">Items</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link scrollto" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                        </li>

                    }
                    else
                    {
                        <li><a class="nav-link scrollto" href="#about">About</a></li>
                        <li><a class="nav-link scrollto" href="#portfolio">Shop</a></li>
                        <li><a class="nav-link scrollto" href="#contact">Contacts</a></li>
                        <li class="nav-item">
                            <a class="nav-link scrollto" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scrollto" asp-area="" asp-controller="Register" asp-action="Index">Register</a>
                        </li>

                    }
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>


        </div>
    </header><!-- End Header -->

    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Enache Alina
        </div>
    </footer>

    <!-- Vendor JS Files -->
    <script src="/vendor/aos/aos.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="/vendor/php-email-form/validate.js"></script>
    <script src="/vendor/purecounter/purecounter.js"></script>
    <script src="/vendor/swiper/swiper-bundle.min.js"></script>

    <!-- Template Main JS File -->
    <script src="/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>